
'use client';

import { PublicNavbar } from '@/components/layout/PublicNavbar';
import { PublicFooter } from '@/components/layout/PublicFooter';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { FileText } from 'lucide-react';
import Link from 'next/link';

export default function TermsAndConditionsPage() {
  const staticDate = "June 12, 2025 IST";

  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-br from-background to-secondary/10">
      <PublicNavbar />
      <main className="flex-1 py-16 md:py-24">
        <div className="container mx-auto px-[5vw] md:px-[10vw]">
          <header className="mb-12 text-center">
            <FileText className="h-16 w-16 text-primary mx-auto mb-4" />
            <h1 className="text-4xl sm:text-5xl font-bold tracking-tighter font-headline text-foreground">
              Terms and Conditions
            </h1>
          </header>

          <Card className="shadow-lg">
            <CardContent className="prose prose-sm dark:prose-invert max-w-none py-8 px-6 md:px-8 space-y-6">
              <p><strong>Effective Date:</strong> {staticDate}<br />
              <strong>Last Updated:</strong> August 1, 2025 IST</p>

              <h2 className="text-xl font-semibold mt-6 mb-3">1. Introduction & Acceptance of Terms</h2>
              <p>Welcome to <strong>FollowUps</strong> — your outreach management assistant. These Terms and Conditions ("<strong>Terms</strong>") form a legally binding agreement between you ("<strong>you</strong>", "<strong>your</strong>", or "<strong>User</strong>") and <strong>FollowUps</strong> ("<strong>FollowUps</strong>", "<strong>we</strong>", "<strong>us</strong>", or "<strong>our</strong>") and govern your use of the FollowUps web application, website (<a href="https://followups.tech">followups.tech</a>), and related services (collectively, the "<strong>Service</strong>").</p>
              <p>By using our Service, you accept these Terms and our <Link href="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link>, which is incorporated by reference. If you do not agree, do not use the Service.</p>
              <p>You must be <strong>at least 18 years old</strong> to access or use FollowUps.</p>

              <h2 className="text-xl font-semibold mt-6 mb-3">2. Account Registration & Security</h2>
              <ul>
                <li>You must create an account to use certain features.</li>
                <li>You agree to provide accurate, complete information and keep it updated.</li>
                <li>You’re responsible for safeguarding your credentials and any activity under your account.</li>
                <li>Only one account per user is permitted.</li>
              </ul>

              <h2 className="text-xl font-semibold mt-6 mb-3">3. The Service</h2>
              <p>FollowUps helps users track leads, schedule follow-ups, and organize communication. We grant you a <strong>limited, revocable, non-exclusive, non-transferable</strong> license to use the Service as per these Terms.</p>
              <p>We reserve the right to modify, suspend, or discontinue any part of the Service at our sole discretion.</p>
              
              <h3 className="text-lg font-semibold mt-4 mb-2">3.1 AI-Powered Features</h3>
              <p>Our Service includes optional AI features powered by Google's Gemini models. To use these features, you must provide your own Gemini API key. By using these features, you agree that:</p>
              <ul>
                  <li>Your API key is stored **only in your browser's local storage** and is never sent to our servers.</li>
                  <li>Prompts you submit (which may contain data you've entered, like job descriptions or resume details) are sent directly from your browser to the Google Gemini API. We do not see, store, or log these prompts or the generated responses.</li>
                  <li>Your use of Google's AI services is subject to Google's own <a href="https://ai.google.dev/terms" target="_blank" rel="noopener noreferrer">Terms of Service</a> and <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a>.</li>
                  <li>We are not responsible for the accuracy, quality, or appropriateness of content generated by the AI. You are solely responsible for reviewing and using any AI-generated content.</li>
              </ul>


              <h2 className="text-xl font-semibold mt-6 mb-3">4. User-Generated Content</h2>
              <h3 className="text-lg font-semibold mt-4 mb-2">a. Ownership & Rights</h3>
              <p>You retain ownership of all content you input into the Service (“<strong>User Content</strong>”), including your resume and portfolio details. By uploading content, you grant us a <strong>worldwide, royalty-free, non-exclusive, sublicensable license</strong> to use, display, and process your content solely for providing and improving the Service.</p>

              <h3 className="text-lg font-semibold mt-4 mb-2">b. User Responsibilities</h3>
              <p>You confirm you own or have legal rights to all content you upload. You’re solely responsible for any consequences of posting it.</p>

              <h3 className="text-lg font-semibold mt-4 mb-2">c. Content Restrictions</h3>
              <p>You may not upload content that is unlawful, defamatory, abusive, harmful, or infringes on others' rights.</p>

              <h3 className="text-lg font-semibold mt-4 mb-2">d. DMCA and Infringement Claims</h3>
              <p>If you believe your copyrighted work has been used inappropriately, please send a takedown request to <a href="mailto:followups.contact@gmail.com" className="text-primary hover:underline">followups.contact@gmail.com</a> in accordance with the <a href="https://www.copyright.gov/dmca/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">DMCA</a>.</p>

              <h2 className="text-xl font-semibold mt-6 mb-3">5. Fees, Payment & Subscriptions</h2>
              <ul>
                <li>Subscription plans are available in Free, Pro, and Business tiers.</li>
                <li>Payments are processed via <strong>Razorpay</strong>. You agree to Razorpay’s terms.</li>
                <li>All fees are in <strong>INR or USD</strong> as selected by you.</li>
                <li>Our plans are pre-paid for a fixed term and do **not** auto-renew.</li>
                <li><strong>No refunds</strong> will be provided unless required by law. Please see our <Link href="/refund-policy" className="text-primary hover:underline">Refund Policy</Link> for details.</li>
                <li>You’re responsible for applicable taxes.</li>
                <li><strong>Free Tier Limitations</strong>: Usage restrictions apply. Exceeding limits may prevent new entries.</li>
                <li><strong>Grace Periods</strong>: If a paid plan expires, a grace period (typically 7 days) applies before premium feature restrictions begin.</li>
              </ul>
              
              <h2 className="text-xl font-semibold mt-6 mb-3">6. Intellectual Property</h2>
              <ul>
                <li>The FollowUps Service, its content (excluding User Content), trademarks, and branding are owned by FollowUps and protected by law.</li>
                <li>Use of our name or logo requires our prior written permission.</li>
              </ul>

              <h2 className="text-xl font-semibold mt-6 mb-3">7. Prohibited Conduct</h2>
              <p>You may not:</p>
              <ul>
                <li>Violate any applicable laws or third-party rights.</li>
                <li>Post harmful, illegal, or infringing content.</li>
                <li>Impersonate others or misrepresent affiliations.</li>
                <li>Interfere with the integrity or performance of the Service.</li>
                <li>Use bots or scraping tools without written permission.</li>
                <li>Reverse-engineer or modify any part of the Service.</li>
              </ul>

              <h2 className="text-xl font-semibold mt-6 mb-3">8. Third-Party Services & Links</h2>
              <p>We use and may link to third-party platforms like <strong>Razorpay</strong>, <strong>Supabase</strong>, and <strong>Google AI</strong>. Your use of such platforms is at your own risk and subject to their respective terms and privacy policies.</p>

              <h2 className="text-xl font-semibold mt-6 mb-3">9. Termination</h2>
              <ul>
                <li>You may terminate your account anytime through account settings or by emailing <a href="mailto:followups.contact@gmail.com" className="text-primary hover:underline">followups.contact@gmail.com</a>.</li>
                <li>We may suspend or terminate your access immediately for violating these Terms.</li>
                <li>Upon termination, your license to use the Service ceases, but rights that should survive (e.g., liability limitations) will continue.</li>
              </ul>

              <h2 className="text-xl font-semibold mt-6 mb-3">10. Disclaimer of Warranties</h2>
              <p><strong>THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.”</strong></p>
              <p>We disclaim all warranties, express or implied, including those of <strong>merchantability</strong>, <strong>fitness for a particular purpose</strong>, and <strong>non-infringement</strong>. We don’t guarantee uninterrupted service or error correction.</p>
              
              <h3 className="text-lg font-semibold mt-4 mb-2">10.1 Accessibility</h3>
              <p>We strive to make our Service accessible to all users. While we work towards complying with standards like the Web Content Accessibility Guidelines (WCAG), we cannot guarantee full compliance at all times. We welcome feedback on how to improve accessibility.</p>


              <h2 className="text-xl font-semibold mt-6 mb-3">11. Limitation of Liability</h2>
              <p>To the <strong>maximum extent permitted by law</strong>, FollowUps, its affiliates, and its personnel shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the service; (ii) any conduct or content of any third party on the service; (iii) any content obtained from the service; and (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage.</p>
              <p>In no event shall our aggregate liability for all claims related to the service exceed the amount paid by you, if any, for access to or use of the service during the twelve (12) month period preceding the claim.</p>


              <h2 className="text-xl font-semibold mt-6 mb-3">12. Indemnification</h2>
              <p>You agree to indemnify and hold FollowUps and its affiliates, agents, and employees harmless from any claims, damages, or liabilities arising from:</p>
              <ul>
                <li>Your use of the Service.</li>
                <li>Content you post.</li>
                <li>Your violation of these Terms.</li>
              </ul>

              <h2 className="text-xl font-semibold mt-6 mb-3">13. Governing Law & Dispute Resolution</h2>
              <p>These Terms are governed by the laws of <strong>India</strong>, excluding conflict of law rules.</p>
              <h3 className="text-lg font-semibold mt-4 mb-2">Dispute Process:</h3>
              <p>First, try to resolve disputes with us <strong>informally</strong> by contacting <a href="mailto:followups.contact@gmail.com" className="text-primary hover:underline">followups.contact@gmail.com</a>.</p>
              <p><strong>Note for Indian users</strong>: We comply with India's <strong>DPDPA</strong>. You may reach our <strong>Grievance Officer</strong> at <a href="mailto:followups.contact@gmail.com" className="text-primary hover:underline">followups.contact@gmail.com</a>.</p>
              <p><strong>Note for EU users</strong>: You have a <strong>14-day right to withdraw</strong> from a paid subscription under the <strong>EU Consumer Rights Directive</strong>. To exercise this right, you must contact us at <a href="mailto:followups.contact@gmail.com" className="text-primary hover:underline">followups.contact@gmail.com</a> within 14 days of your purchase. Please note that this right may be waived if you begin using the paid features of the service immediately.</p>


              <h2 className="text-xl font-semibold mt-6 mb-3">14. Changes to These Terms</h2>
              <p>We may update these Terms at our sole discretion. If we make material changes, we’ll provide <strong>at least 30 days' notice</strong> via email or our app.</p>
              <p>Continued use after updates means you accept the revised Terms.</p>

              <h2 className="text-xl font-semibold mt-6 mb-3">15. Miscellaneous</h2>
              <ul>
                <li><strong>Entire Agreement</strong>: These Terms and the Privacy Policy form the entire agreement.</li>
                <li><strong>Severability</strong>: If any part is unenforceable, the rest remains in effect.</li>
                <li><strong>Waiver</strong>: Failure to enforce a right isn’t a waiver.</li>
                <li><strong>Assignment</strong>: You may not transfer your rights; we may assign ours.</li>
                <li><strong>Headings</strong>: Are for convenience only and have no legal effect.</li>
              </ul>

              <h2 className="text-xl font-semibold mt-6 mb-3">16. Contact Information</h2>
              <ul>
                <li><strong>Email</strong>: <a href="mailto:followups.contact@gmail.com" className="text-primary hover:underline">followups.contact@gmail.com</a></li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </main>
      <PublicFooter />
    </div>
  );
}
